name: push
on:
  push:
jobs:
  launcher:
    name: Launcher
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create artifacts
        run: |
          mkdir -p artifacts
          mv Launcher/build/libs/Launcher.jar artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Launcher
          path: artifacts
