name: push
on:
  push:
jobs:
  launcher:
    name: Launcher
    runs-on: windows-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 8
        uses: joschi/setup-jdk@v2
        with:
         java-version: '8' # The OpenJDK version to make available on the path
         architecture: 'x64' # defaults to 'x64'

      - name: Build with Gradle
        run: ./gradlew.bat build

      - name: Create artifacts
        run: |
          mkdir artifacts
          move Launcher\build\libs\Launcher.jar artifacts
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Launcher
          path: artifacts
